server:
  servlet:
    context-path: /${spring.application.name}
spring:  jackson:    serialization:      indent-output: true
  security:    user:      name: user
      password: password
      roles:      - USER
  data:
    mongodb:
      database: rsi
      uri: mongodb+srv://${mongo.user}:${mongo.password}@${mongo.host}/${mongo.db}?retryWrites=true&w=majority
market-data:
  path: classpath*:*/*.csv
