server:
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: trade-planner  jackson:    serialization:      indent-output: true
  security:    user:      name: user
      password: password
      roles:      - USER
  data:
    mongodb:
      database: rsi
      uri: mongodb+srv://<user>:<password>@cluster0-v3bj2.mongodb.net/rsi?retryWrites=true&w=majority
market-data:
  path: classpath*:*/*.csv